config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'

  resources :users, except: [:index, :destroy]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'edit', to: 'sessions#edit'
  post 'passwd', to: 'sessions#update'
  get 'welcome', to: 'sessions#welcome'
  
  # resources :sessions, only: [:new, :create, :destroy]
  resources :contracts, only: [:index, :show]
  resources :products, only: [:index, :show]
  
  get "*path" => redirect("/")
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = "salesforce.contact"

  validates :email, :uniqueness => true, :presence => true
  validates :phone, :allow_blank => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }

  validates :mobilephone, :allow_blank => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }

  def password
    return encrypted_password__c
  end

  # def password_digest=(value)
  #   return encrypted_password__c
  # end

  def self.hash_password(password)
    BCrypt::Password.create(password).to_s
  end

  def valid_password(pass)
    BCrypt::Password.new(self.encrypted_password__c) == pass
  end

  def contracts
    Contract.where({accountid: self.accountid})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: %i[ new create ]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

    # GET /users/1 or /users/1.json
  def show
    #@contracts = @user.contracts
  end

  # GET /users/new
  def new
    if logged_in?
      respond_to do |format|
        format.html { redirect_to '/welcome' }
        format.json { head :no_content }
      end
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    if logged_in?
      respond_to do |format|
        format.html { redirect_to '/welcome' }
        format.json { head :no_content }
      end
    end
    ok = false
    result = ""
    @user_params = user_params
    Rails.logger.debug "PARAMS : #{@user_params}"
    @user = User.where({ email: @user_params[:email] }).last
    
    if @user.nil?
      result = "created"
      password = @user_params[:encrypted_password__c]
      Rails.logger.debug "PASS : #{password}"
      @user_params[:encrypted_password__c] = User.hash_password(password)
      @user_params[:extid__c] = @user_params[:encrypted_password__c]
      @user = User.new(user_params)
      ok = @user.save
    elsif  @user.encrypted_password__c.nil?
      result = "updated"
      @user_params[:encrypted_password__c] = User.hash_password(@user_params[:encrypted_password__c])
      ok = @user.update(@user_params)
    else
      ok = false
      result = "An account with this email exists."
    end

    respond_to do |format|
      if ok
        session[:user_id] = @user.id
        format.html { redirect_to '/welcome', notice: "User was successfully #{result}" }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:notice] = result
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # def create
  #    @user = User.create(params.require(:user).permit(:username,
  #    :password))
  #    session[:user_id] = @user.id
  #    redirect_to '/welcome'
  # end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    ok = false
    result = ""
    @user_params = user_params
    password = @user_params[:encrypted_password__c]
    Rails.logger.debug "PASSWORD #{password}"
    if @user.valid_password(password)
      Rails.logger.debug "VALID PASSWORD"
      @user_params[:encrypted_password__c] = User.hash_password(password)
      if @user.update(@user_params)
        ok = true
        result = "Profile was successfully updated."
      else
        result = "Impossible to update profile"
      end
    else
      Rails.logger.debug "INVALID PASSWORD"
      result = "Please confirm your password"
    end

    respond_to do |format|
      if ok
        format.html { redirect_to @user, notice: result }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:notice] = result
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /users/1 or /users/1.json
  # def destroy

  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: "User was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    @user_params ||= params.require(:user).permit(:firstname, :lastname, :email, :phone, :mobilephone, :mailingcity, :mailingcountry, :mailingpostalcode, :mailingstate, :mailingstreet, :encrypted_password__c)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :firstname %>*
    <%= form.text_field :firstname, {class: "form-control", placeholder: "First Name", required: true} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :lastname %>*
    <%= form.text_field :lastname, {class: "form-control", placeholder: "Last Name", required: true} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :email %>*
    <%= form.email_field :email, {class: "form-control", placeholder: "Email", required: true} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :phone %>
    <%= form.telephone_field :phone, {class: "form-control", placeholder: "Phone Number"} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :mobilephone %>
    <%= form.telephone_field :mobilephone, {class: "form-control", placeholder: "Mobile Phone Number"} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :mailingstreet %>
    <%= form.text_field :mailingstreet, {class: "form-control", placeholder: "Mailing Street"} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :mailingcity %>
    <%= form.text_field :mailingcity, {class: "form-control", placeholder: "Mailing City"} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :mailingpostalcode %>
    <%= form.text_field :mailingpostalcode, {class: "form-control", placeholder: "Mailing Postal Code"} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :mailingstate %>
    <%= form.text_field :mailingstate, {class: "form-control", placeholder: "Mailing State"} %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :mailingcountry %>
    <%= form.text_field :mailingcountry, {class: "form-control", placeholder: "Mailing Country"} %>
  </div>
  <br />
  <div class="form-group">
     <% if current_user %>
      <%= form.label :encrypted_password__c, 'Confirm your Password*' %>
    <% else %>
      <%= form.label :encrypted_password__c, 'Choose a Password*' %>
    <% end %>
    <%= form.password_field :encrypted_password__c, {class: "form-control", required: true} %>
  </div>
  <br />
  <p>* Mandatory fields</p>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<div  class="container p-3 my3">
  <%= render 'form', user: @user %>
</div>
<%= link_to 'Back', @user, {class: "btn btn-info"} %>

app/views/users/new.html.erb
<h1>Create your account</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<h1>My profile</h1>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Account Id:</strong>
  <%= @user.accountid %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @user.mobilephone %>
</p>

<p>
  <strong>Mailing street:</strong>
  <%= @user.mailingstreet %>
</p>

<p>
  <strong>Mailing city:</strong>
  <%= @user.mailingcity %>
</p>

<p>
  <strong>Mailing postal code:</strong>
  <%= @user.mailingpostalcode %>
</p>

<p>
  <strong>Mailing state:</strong>
  <%= @user.mailingstate %>
</p>

<p>
  <strong>Mailing country:</strong>
  <%= @user.mailingcountry %>
</p>

<%= link_to 'Edit', edit_user_path(@user),  {class: "btn btn-info"} %>
<br />
<br />
<%= link_to 'Modify password', "/edit",  {class: "btn btn-info"} %>
<br />
<br />
<%= link_to 'My contracts', contracts_path,  {class: "btn btn-info"} %>